# Generated by Django 5.1.3 on 2024-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmpRazborTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_pacienta', models.CharField(max_length=250)),
                ('rezultat_vyzova', models.CharField(max_length=255)),
                ('aktiv_passiv', models.CharField(max_length=255)),
                ('diagnoz_po_mkb', models.CharField(max_length=255)),
                ('prichina_vyzova_skoroiy_pomoschi', models.TextField()),
                ('nalichie_bolevogo_sindroma', models.CharField(max_length=255)),
                ('prichina_vyzova_skoroiy_pomoschi_kratko', models.TextField()),
                ('kuriruyushchee_podrazdelenie_ovpp', models.CharField(max_length=255)),
                ('dejstviya_cpp', models.TextField()),
                ('byl_li_ustanovlen_bazovyj_plan_na_poslednem_vizite', models.CharField(max_length=255)),
                ('otobrazheny_li_vse_zhaloby_pacienta_v_polnom_obeme', models.CharField(max_length=255)),
                ('dinamika_sostoyaniya', models.CharField(max_length=255)),
                ('kakova_prichina_vyzova_smp_po_rezutatam_audiokontrolya', models.TextField()),
                ('kakie_dejstviya_byli_predprinyaty_smp', models.TextField()),
                ('tekushchee_sostoyanie_pacienta_posle_vyzova_smp', models.TextField()),
                ('ostalis_li_zhaloby_posle_vyzova_smp', models.CharField(max_length=255)),
                ('opisanie_zhalob', models.TextField()),
                ('byli_li_lekarstvennye_sredstva_otovareny_po_receptu', models.TextField()),
                ('pacient_prinimaet_naznachennye_lekarstvennye_sredstva', models.CharField(max_length=255)),
                ('ehffektivna_li_naznachennaya_medikamentoznaya_terapiya', models.CharField(max_length=255)),
                ('est_li_pobochnye_dejstviya_ot_naznachennykh_lekarstvennykh', models.CharField(max_length=255)),
                ('pacientu_byla_ozvuchena_data_sleduyushchego_vizita', models.CharField(max_length=255)),
                ('pacientu_byli_predostavleny_kontaktnye_nomera_cpp', models.CharField(max_length=255)),
                ('pacient_zvonil_po_ukazannym_kontaktnym_nomera_do_vyzova_smp', models.CharField(max_length=255)),
                ('prichina_po_kotoroj_pacient_ne_zvonil_po_ukazannym_nomeram', models.TextField()),
                ('sootvetstvuet_li_naznachennyj_bazovyj_plan_sostoyaniyu_pacie', models.CharField(max_length=255)),
                ('trebovanie_gospitalizacii_na_dannyj_moment', models.CharField(max_length=255)),
                ('bazovyj_plan_naznachen_korrektno', models.CharField(max_length=255)),
                ('ocenka_sostoyaniya_sootvetstvuet_bazovomu_planu', models.CharField(max_length=255)),
                ('zhaloby_opisany_v_polnom_obeme', models.CharField(max_length=255)),
                ('ocenka_zaveduyushchego_proizvedena_korrektno', models.CharField(max_length=255)),
                ('vyvody_po_rezultatm_ocenki', models.TextField()),
                ('vyyavlennye_defekty_v_rabote_vracha', models.TextField()),
                ('ocenka_dejstvij_vracha_do_vyzova_smp', models.TextField()),
                ('ocenka_dejstvij_posle_vyzova_smp', models.TextField()),
                ('analiz_dejstvij_glavnym_vrachom', models.TextField()),
                ('polis_oms', models.TextField()),
                ('p_p', models.IntegerField()),
                ('kolichestvo_vyezdov_v_den', models.IntegerField()),
                ('kolichestvo_dnej_ot_momenta_polucheniya_dannykh_po_smp_do_sover', models.IntegerField()),
                ('kolichestvo_dnej_ot_proshlogo_vizita_vracha', models.IntegerField()),
                ('kakaya_data_sleduyushchego_vizita_vracha_soglasno_protokolu', models.DateField()),
                ('data_poslednego_vizita_vracha_iz_protokola_osmotra_emias', models.DateField()),
                ('data_naznachenogo_audioprotokola_soglasno_protokolu_v', models.DateField()),
                ('data_polucheniya_svedenij_po_vyzovam_smp_ot_kc', models.DateField()),
                ('data_audioprotokola_posle_polucheniya_dannykh_o_vyzove_smp', models.DateField()),
                ('data_vyzova_smp', models.DateField()),
                ('data_rozhdeniya', models.DateField()),
                ('data_vklyucheniya_v_registr', models.DateField()),
            ],
            options={
                'db_table': 'smp_razbor_tab',
            },
        ),
    ]
