# Generated by Django 5.1.3 on 2024-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0002_alter_smprazbortab_aktiv_passiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='kakova_prichina_vyzova_smp_po_rezutatam_audiokontrolya',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kolichestvo_dnej_ot_momenta_polucheniya_dannykh_po_smp_do_sover',
            field=models.IntegerField(null=True),
        ),
    ]
