# Generated by Django 5.1.3 on 2024-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0003_alter_smprazbortab_kakova_prichina_vyzova_smp_po_rezutatam_audiokontrolya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smprazbortab',
            name='fio_vracha',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smprazbortab',
            name='kontrol_ispolneniya_naznachennykh_vrachom_cpp_rekomendacij',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smprazbortab',
            name='sravnenie_povoda_vyz_smp_s_prot_vracha_cpp_do_i_posle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smprazbortab',
            name='vyvod',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
