# Generated by Django 5.1.3 on 2024-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0004_smprazbortab_fio_vracha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='aktiv_passiv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='analiz_dejstvij_glavnym_vrachom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='bazovyj_plan_naznachen_korrektno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='byl_li_ustanovlen_bazovyj_plan_na_poslednem_vizite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='byli_li_lekarstvennye_sredstva_otovareny_po_receptu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_audioprotokola_posle_polucheniya_dannykh_o_vyzove_smp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_naznachenogo_audioprotokola_soglasno_protokolu_v',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_polucheniya_svedenij_po_vyzovam_smp_ot_kc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_poslednego_vizita_vracha_iz_protokola_osmotra_emias',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_rozhdeniya',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='data_vyzova_smp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='dejstviya_cpp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='diagnoz_po_mkb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='dinamika_sostoyaniya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ehffektivna_li_naznachennaya_medikamentoznaya_terapiya',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='est_li_pobochnye_dejstviya_ot_naznachennykh_lekarstvennykh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='fio_vracha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kakaya_data_sleduyushchego_vizita_vracha_soglasno_protokolu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kakie_dejstviya_byli_predprinyaty_smp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kakova_prichina_vyzova_smp_po_rezutatam_audiokontrolya',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kolichestvo_dnej_ot_momenta_polucheniya_dannykh_po_smp_do_sover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kolichestvo_dnej_ot_proshlogo_vizita_vracha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kolichestvo_vyezdov_v_den',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kontrol_ispolneniya_naznachennykh_vrachom_cpp_rekomendacij',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='kuriruyushchee_podrazdelenie_ovpp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='nalichie_bolevogo_sindroma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ocenka_dejstvij_posle_vyzova_smp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ocenka_dejstvij_vracha_do_vyzova_smp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ocenka_sostoyaniya_sootvetstvuet_bazovomu_planu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ocenka_zaveduyushchego_proizvedena_korrektno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='opisanie_zhalob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='ostalis_li_zhaloby_posle_vyzova_smp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='otobrazheny_li_vse_zhaloby_pacienta_v_polnom_obeme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='p_p',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='pacient_prinimaet_naznachennye_lekarstvennye_sredstva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='pacient_zvonil_po_ukazannym_kontaktnym_nomera_do_vyzova_smp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='pacientu_byla_ozvuchena_data_sleduyushchego_vizita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='pacientu_byli_predostavleny_kontaktnye_nomera_cpp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='polis_oms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='prichina_po_kotoroj_pacient_ne_zvonil_po_ukazannym_nomeram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='prichina_vyzova_skoroiy_pomoschi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='prichina_vyzova_skoroiy_pomoschi_kratko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='rezultat_vyzova',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='sootvetstvuet_li_naznachennyj_bazovyj_plan_sostoyaniyu_pacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='sravnenie_povoda_vyz_smp_s_prot_vracha_cpp_do_i_posle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='tekushchee_sostoyanie_pacienta_posle_vyzova_smp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='trebovanie_gospitalizacii_na_dannyj_moment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='vyvod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='vyvody_po_rezultatm_ocenki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='zhaloby_opisany_v_polnom_obeme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
