# Generated by Django 5.1.3 on 2024-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0006_alter_smprazbortab_data_vklyucheniya_v_registr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='polis_oms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
