# Generated by Django 5.1.3 on 2024-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0007_alter_smprazbortab_polis_oms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='dejstviya_cpp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='prichina_vyzova_skoroiy_pomoschi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smprazbortab',
            name='prichina_vyzova_skoroiy_pomoschi_kratko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
