# Generated by Django 5.1.3 on 2024-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0008_alter_smprazbortab_dejstviya_cpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smprazbortab',
            name='ok_vps',
            field=models.BooleanField(default=False),
        ),
    ]
