# Generated by Django 5.1.3 on 2024-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0009_smprazbortab_ok_vps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='rezultat_vyzova',
            field=models.TextField(blank=True, null=True),
        ),
    ]
