# Generated by Django 5.1.3 on 2024-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0012_alter_smprazbortab_analiz_dejstvij_glavnym_vrachom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='rezultat_vyzova',
            field=models.TextField(blank=True),
        ),
    ]
