# Generated by Django 5.1.3 on 2024-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_smp', '0014_alter_smprazbortab_aktiv_passiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smprazbortab',
            name='ok_vps',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
